#!/usr/bin/env bash
#
# scripts/fetch-gcp-env.sh
# Fetches deployment coordinates from gcloud and writes them to secrets/gcp.env
# (which is gitignored). This script is safe to commit — it contains no secrets,
# it only retrieves them.
#
# Usage:
#   ./scripts/fetch-gcp-env.sh
#   INSTANCE=other-name ZONE=us-east1-b ./scripts/fetch-gcp-env.sh
#   # or: npm run gcp:env

set -euo pipefail

INSTANCE="${INSTANCE:-game-of-life}"

ZONE_RAW="$(gcloud config get-value compute/zone 2>/dev/null || echo '')"
if [[ -z "$ZONE_RAW" || "$ZONE_RAW" == "(unset)" ]]; then
  ZONE="${ZONE:-us-central1-a}"
else
  ZONE="$ZONE_RAW"
fi

PROJECT_RAW="$(gcloud config get-value core/project 2>/dev/null || echo '')"
if [[ -z "$PROJECT_RAW" || "$PROJECT_RAW" == "(unset)" ]]; then
  echo "ERROR: no gcloud project configured. Run: gcloud config set project YOUR_PROJECT" >&2
  exit 1
fi
PROJECT="$PROJECT_RAW"

REGION="${ZONE%-*}"  # us-central1-a -> us-central1

echo "[fetch] project=$PROJECT zone=$ZONE instance=$INSTANCE"

DESC=(gcloud compute instances describe "$INSTANCE" --zone="$ZONE")

EXT_IP="$("${DESC[@]}" --format='value(networkInterfaces[0].accessConfigs[0].natIP)' 2>/dev/null || echo '')"
INT_IP="$("${DESC[@]}" --format='value(networkInterfaces[0].networkIP)' 2>/dev/null || echo '')"
MACHINE_URL="$("${DESC[@]}" --format='value(machineType)' 2>/dev/null || echo '')"
MACHINE="${MACHINE_URL##*/}"
SA="$("${DESC[@]}" --format='value(serviceAccounts[0].email)' 2>/dev/null || echo '')"
STATUS="$("${DESC[@]}" --format='value(status)' 2>/dev/null || echo '')"

mkdir -p secrets
OUT="secrets/gcp.env"

cat > "$OUT" <<ENV
# Generated by scripts/fetch-gcp-env.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# DO NOT COMMIT — this file is gitignored.
#
# These are deployment coordinates, NOT access credentials.
# (Put real secrets — tokens, keys — here too if you add any, and keep them
# out of git; the whole secrets/ folder is ignored except *.example files.)

GCP_PROJECT_ID="$PROJECT"
GCP_REGION="$REGION"
GCP_ZONE="$ZONE"
GCP_INSTANCE="$INSTANCE"
GCP_STATUS="$STATUS"
GCP_MACHINE_TYPE="$MACHINE"
GCP_INTERNAL_IP="$INT_IP"
GCP_EXTERNAL_IP="$EXT_IP"
GCP_APP_URL="http://${EXT_IP}:3000"
GCP_SERVICE_ACCOUNT="$SA"

# Quick access:
#   source secrets/gcp.env
#   curl "$GCP_APP_URL/api/brushes"
#   gcloud compute ssh "$GCP_INSTANCE" --zone="$GCP_ZONE"
#   gcloud compute instances start "$GCP_INSTANCE" --zone="$GCP_ZONE"
#   gcloud compute instances stop  "$GCP_INSTANCE" --zone="$GCP_ZONE"
ENV

echo "[fetch] wrote $OUT"
echo "----- $OUT -----"
cat "$OUT"
